FROM node:slim

WORKDIR /app

RUN apt update && \
  apt -y upgrade

RUN apt install -y vim

RUN npm install -g @angular/cli

RUN apt -y autoremove

COPY entrypoint.sh /scripts/entrypoint.sh

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD "ng serve --open --host 0.0.0.0"