FROM debian:testing-slim

WORKDIR /app

ENV $PATH=/app/playarea/node_modules/.bin:${PATH}

RUN apt update && \
  apt -y dist-upgrade

RUN apt install -y python3 python3-pip nodejs npm vim gettext

RUN if [ ! -f /usr/bin/pip ]; then ln -s /usr/bin/pip3 /usr/bin/pip; fi

RUN pip install autopep8 django gTTS psycopg2-binary djangorestframework markdown django-filter djongo gunicorn Pillow

RUN pip install ptvsd debugpy

RUN apt -y autoremove

RUN mkdir -p /root/.local/bin && \
  ln -s /usr/local/bin/autopep8 /root/.local/bin/autopep8

COPY ./entrypoint.sh /scripts/entrypoint.sh

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]