FROM debian:testing-slim

WORKDIR /app

ENV $PATH=/app/playarea/node_modules/.bin:${PATH}

RUN apt update && \
  apt -y dist-upgrade

RUN apt install -y python3 python3-pip nodejs npm vim

RUN if [ ! -f /usr/bin/pip ]; then ln -s /usr/bin/pip3 /usr/bin/pip; fi

RUN pip install django gTTS psycopg2-binary djangorestframework markdown django-filter djongo gunicorn

RUN pip install ptvsd debugpy

RUN apt -y autoremove

COPY ./entrypoint.sh /scripts/entrypoint.sh

ENTRYPOINT [ "/scripts/entrypoint.sh" ]

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]