# Generated by Django 3.0.5 on 2021-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_create_test_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('name_stringified', models.CharField(blank=True, max_length=220, null=True)),
                ('href', models.CharField(max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('name_stringified', models.CharField(blank=True, max_length=220, null=True)),
                ('href', models.CharField(blank=True, max_length=220, null=True)),
                ('subApps', models.ManyToManyField(to='main.SubApp')),
            ],
        ),
    ]
