FROM mongo

RUN apt update && \
  apt -y dist-upgrade 

RUN apt -y install vim

ENV MONGO_INITDB_ROOT_USERNAME admin
ENV MONGO_INITDB_ROOT_PASSWORD=password
ENV MONGO_INITDB_DATABASE playarea-db
ENV MONGODB_USERNAME playarea-admin
ENV MONGODB_PASSWORD playarea-password

ADD ./initDB.js /docker-entrypoint-initdb.d/initDB.js