# Generated by Django 3.0.5 on 2021-07-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, unique=True)),
                ('modified', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_clone.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notation', models.CharField(max_length=4)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_clone.Table')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('modified', models.DateTimeField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_clone.Column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_clone.Row')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_clone.Table')),
            ],
        ),
    ]
