BBBB BBBBBB

XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXXX

    XXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
    XX
    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX
    XXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXX

    XXXXXXX XXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBX
    XXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXX
    XXXXXXX XXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXX
    
    BBBBB BBBB BBBBBBBB BBBB
  XXXXXXX
  XXXXXX
    BBBBB BBBBBBBBBB BBBBBBBB BBBBBBBBBB
    BBBBB BBBBBBB BBBBBBBB BBBBBBB
    BBBBB BBBBBB BBBBBBBB BBBBBB
    BBBBB BB BBBBBBBB BB
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXXX
