BBBB BBBBBB

XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBB
  XXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
  X
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

    XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXX XXXXXXXXXX XXXXXXXXXX
      XX 
        XXXXXXXX 
        XXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXXXX 
        XXXXXXXXXXXXXXXXXXXXX
      X
        XXXX 
          XXXXXX 
          XXXXXXX XXXXXXXX 
          XXXXXXXXXXXXXXXXXXXXX  
        X
      XXXX
      XXXX 
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      X
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXBBB BBBBBBBBBBBXXX XXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXBBB BBBBBBBBXXXXXXXXXXX
      XXXXXX
    XXXXXX
  BBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXBBB BBBBBBB XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        XXXXX
      XXXX
    XXXXXX
  BBBBB
  XXXXXX
XXXXXX

BB BB
  XXXXXXXX
  XBB BBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBX
  XXXXXXXXXXX X XXXXXXXXXXXXFFFFFFFFFFFFXXX
  XBBBBBX
  XXXXXXXXX
BBBBB
